version: "3"
services:
  portainer:
    image: portainer/portainer
    ports:
      - "9100:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
          - portainer