version: "3"
services:
 flask:
    build:
      context: flask_app
    image: "flask:dev"
    ports:
      - "5010:5000"
    depends_on:
      - mongo
    volumes:
      - ./flask_app:/opt/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]  # Always return error
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      backend:
        aliases:
          - flask
  mongo:
    image: "mongo"
    ports:
      - "27018:27017"
networks:
  backend:
    driver: bridge