version: 2.1

commands:
  installDeps:
    description: "Install pipenv and dependencies"
    steps:
      - run:
          name: "Install Pipenv"
          command: pip install -U --user pipenv
      - run:
          name: "Build"
          command: sudo pip install -e .

jobs:
  build_test_python3.5:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - installDeps
      - run:
          name: Test
          command: make ci
  build_test_python3.6:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - installDeps
      - run:
          name: Test
          command: make ci
      - run:
          name: Send coverage
          command: codecov
  build_test_python3.7:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - installDeps
      - run:
          name: Test
          command: make ci
  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Changelog Libs
          command: |
            sudo apt-get install -y jq
      - run:
          name: Create Changelog
          command: make changelog
      - run:
          name: Save Release
          command: make release
      - run:
          name: Publish Package
          command: make deploy
workflows:
  version: 2
  deploy:
    jobs:
      - build_test_python3.5
      - build_test_python3.6
      - build_test_python3.7
      - release:
          requires:
            - build_test_python3.5
            - build_test_python3.6
            - build_test_python3.7
          filters:
            branches:
              only:
                - master
