version: 2
jobs:
  build_test_python3.5:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: Install Pipenv
          command: pip install -U --user pipenv
      - run:
          name: Build
          command: sudo pip install -e .
      - run:
          name: Test
          command: make ci
  build_test_python3.6:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install Pipenv
          command: pip install -U --user pipenv
      - run:
          name: Build
          command: sudo pipenv install --system --deploy --dev
      - run:
          name: Test
          command: make ci
      - save_cache:
          key: cache-megalus-{{ .BuildNum }}
          paths:
            - .
  build_test_python3.7:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Pipenv
          command: pip install -U --user pipenv
      - run:
          name: Build
          command: sudo pip install -e .
      - run:
          name: Test
          command: make ci
  coverage:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-megalus-{{ .BuildNum }}
            - cache-megalus-
      - run:
          name: Install codecov
          command: pip install codecov
      - run:
          name: Send Coverage
          command: codecov
  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Changelog Libs
          command: |
            sudo apt-get install -y jq
      - run:
          name: Create Changelog
          command: make changelog
      - run:
          name: Save Release
          command: make release
      - run:
          name: Publish Package
          command: make deploy
workflows:
  version: 2
  deploy:
    jobs:
      - build_test_python3.5
      - build_test_python3.6
      - build_test_python3.7
      - coverage:
          requires:
            - build_test_python3.6
      - release:
          requires:
            - build_test_python3.5
            - build_test_python3.6
            - build_test_python3.7
          filters:
            branches:
              only:
                - master
